apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-t44o
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-t44o@sha256:8383498f998c6441460b1ffc3af949f0997aff16831407664ad7271a357d55fb
        name: my-nodejs
        resources: {}
status: {}
